output "service_name" {
  description = "The simulated service name."
  value       = var.name
}

output "service" {
  description = "Compact summary object describing the simulated service. Useful for environment-level outputs."
  value = {
    name         = var.name
    environment  = var.environment
    image        = var.image
    replicas     = var.replicas
    public       = var.public
    owner        = var.owner
    cost_center  = var.cost_center
    dependencies = var.dependencies
  }
}

output "id" {
  description = "Opaque simulated resource id (generated by terraform_data, known after apply)."
  value       = terraform_data.service.id
}
